#!/bin/bash

usage() {
    echo "$0 [-p <install_prefix>] [-c <build_cores>]"
    exit 0
    }

OPTIND=1

prefix=$HOME/frib-e2sar
cores=1

if [ -z "$DAQROOT" ]; then
    . /usr/opt/daq/12.1-010.e2sar/daqsetup.bash
fi

while getopts ":h?p:c:" opt; do
    case "$opt" in
	h|\?)
	    usage
	    exit 0
	    ;;
	p)
	    prefix=$OPTARG
	    ;;
	c)
	    cores=$OPTARG
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument." >&2
	    usage
	    ;;
    esac
done

shift $((OPTIND - 1))

# Clean build and install:

rm -rf build

(mkdir build ;
 cd build ;
 cmake .. -DNSCLDAQ_ROOT=$DAQROOT -DCMAKE_INSTALL_PREFIX=$prefix ;
 cmake --build . -j$cores;
 cmake --install .)
